server:
  port: 8500
eureka:
  client:
    service-url:
      #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: localhost:8761/eureka
  instance:
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: configserver
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/leizc2016/springcloud-config.git
          clone-on-start: false
          #searchPaths: springcloud-config
          username: leizc2016
          password: 043241xx